# conf/models/xlstm_asr.yaml

_target_: model.model.ASRxLSTM

# Акустические фичи
num_features: 13

# Архитектура xLSTM
hidden_size: 512
num_blocks: 8
num_heads: 8
context_length: 2048
slstm_backend: 'cuda'

# Регуляризация
dropout: 0.1

# Классы (vocab)
num_classes: ${datasets.vocab_size}

# Нормализация mel (обновляется в коде)
mean_global: ${datasets.mel_mean}
std_global: ${datasets.mel_std}

# Дебаг‑режим
debug: ${debug}