# conf/models/xlstm_asr.yaml

_target_: model.model.ASRxLSTM

# Акустические фичи
num_features: 32

# Архитектура xLSTM
hidden_size: 256
num_blocks: 4
num_heads: 4
context_length: 1024
slstm_backend: 'cuda'

# Регуляризация
dropout: 0.1

# Классы (vocab)
num_classes: ${datasets.vocab_size}

# Нормализация mel (обновляется в коде)
mel_mean: ${datasets.mel_mean}
mel_std: ${datasets.mel_std}

# Дебаг‑режим
debug: ${debug}