# conf/trainer/hf_trainer.yaml

# Аргументы HuggingFace TrainingArguments
training_args:
  _target_: transformers.TrainingArguments

  # Куда сохранять чекпоинты/логи
  output_dir: ${output_dir}
  overwrite_output_dir: true

  # Организация батчей
  group_by_length: true
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 2

  # Оптимизация
  learning_rate: 1e-4
  weight_decay: 1e-3
  warmup_ratio: 0.1
  num_train_epochs: 10

  # Стратегии eval/save/logging
  eval_strategy: "steps"
  save_strategy: "steps"
  eval_steps: 100
  save_steps: 1000
  logging_steps: 5

  # Модель для сохранения
  load_best_model_at_end: false
  metric_for_best_model: "eval_wer"
  greater_is_better: false

  # Логирование для TensorBoard
  # report_to: "tensorboard"
  # logging_dir: ${output_dir}/logs

  # Precision и поведение колоночного фильтра
  fp16: true
  remove_unused_columns: false

# DataCollator для ASRxLSTM
data_collator:
  _target_: data.data_process.DataCollatorASRWithPadding

  fixed_n_mels: ${models.num_features}
  max_input_length: 512
  max_labels_length: 256
  padding_value: 0.0
  labels_pad_token_id: -100
